/*
	Created by SIGCAM\g.pezzella using dbatools Export-DbaScript for objects on SIGMANAV01 at 06/22/2026 13:30:11
	See https://dbatools.io/Export-DbaScript for more information
*/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'AIAnalytics')
BEGIN
CREATE DATABASE [AIAnalytics]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AIAnalytics', FILENAME = N'F:\Data\AIAnalytics.mdf' , SIZE = 1424704KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AIAnalytics_log', FILENAME = N'G:\Log\AIAnalytics_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 COLLATE Latin1_General_CI_AS
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
END
GO
ALTER DATABASE [AIAnalytics] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AIAnalytics].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AIAnalytics] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AIAnalytics] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AIAnalytics] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AIAnalytics] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AIAnalytics] SET ARITHABORT OFF 
GO
ALTER DATABASE [AIAnalytics] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AIAnalytics] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AIAnalytics] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AIAnalytics] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AIAnalytics] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AIAnalytics] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AIAnalytics] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AIAnalytics] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AIAnalytics] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AIAnalytics] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AIAnalytics] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AIAnalytics] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AIAnalytics] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AIAnalytics] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AIAnalytics] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AIAnalytics] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AIAnalytics] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AIAnalytics] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AIAnalytics] SET  MULTI_USER 
GO
ALTER DATABASE [AIAnalytics] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AIAnalytics] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AIAnalytics] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AIAnalytics] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AIAnalytics] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AIAnalytics] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
USE [AIAnalytics]
GO
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'AIAnalytics')
CREATE USER [AIAnalytics] FOR LOGIN [AIAnalytics] WITH DEFAULT_SCHEMA=[dbo]
GO
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'SIGCAM\sqlservice')
CREATE USER [SIGCAM\sqlservice] FOR LOGIN [SIGCAM\sqlservice] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER DATABASE [AIAnalytics] SET QUERY_STORE = OFF
GO
GRANT CONNECT TO [AIAnalytics] AS [dbo]
GO
GRANT VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO [public] AS [dbo]
GO
GRANT VIEW ANY COLUMN MASTER KEY DEFINITION TO [public] AS [dbo]
GO
GRANT CONNECT TO [SIGCAM\sqlservice] AS [dbo]
GO
ALTER DATABASE [AIAnalytics] SET  READ_WRITE 
GO
